### ISSUE TITLE
【本リリース】 タイトルスクロールのバグ修正

### ISSUE THREAD

**Issue by massan-E** [massan-E/nanigaderukana#171]
# なぜ必要か
[![Image from Gyazo](https://i.gyazo.com/b490c840b29bb1487e003a155ebe1add.gif)](https://gyazo.com/b490c840b29bb1487e003a155ebe1add)

# 必要なこと
- [ ] 右にスクロールしないようにする

# やること（コードレベル）
- [ ] 以下部分の` @keyframes scrollText `が-100%で左に全部隠すと思ってたけど実は親要素の長さの分左に移動して隠してただけなのでここのロジックを変える

```CSS

@keyframes scrollText {
  0%, 20% {
    transform: translateX(0);
  }
  65%, 90% {
    transform: translateX(calc(-100% + 18em));
  }
  100% {
    transform: translateX(0);
  }
}

@media (max-width: 992px) {
  .text-truncate-container {
    max-height: 10rem;
    overflow: scroll;
  }
  .scroll {
    overflow: hidden;
    width: 100%;
  }
  .title-scroll {
    animation: scrollText 20s infinite;
  }

  @keyframes scrollText {
    0%, 20% {
      transform: translateX(0);
    }
    65%, 90% {
      transform: translateX(calc(-100% + 10em));
    }
    100% {
      transform: translateX(0);
    }
  }
}
```

- [ ] 現在は子要素を親要素分だけ左に隠すって感じやけどそれを以下のようにする
  - 親要素より子要素の方が長くなってしまった場合
    (子要素の長さ) - (親要素の長さ) の分だけアクションでスクロールさせる

# このissueで実装しないもの
- 特になし
